export const ErrorCodes = {
  AUTH_MISSING_FIELDS: "AUTH_MISSING_FIELDS",
  ADMIN_REGISTER_DUPLICATE: "ADMIN_REGISTER_DUPLICATE",
  AUTH_INVALID_USER: "AUTH_INVALID_USER",

  USER_REGISTER_DUPLICATE: "USER_REGISTER_DUPLICATE",
  USER_REGISTER_INVALID: "USER_REGISTER_INVALID",
  USER_ALREADY_ANSWERED_THIS_RANK: "USER_ALREADY_ANSWERED_THIS_RANK",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_USER: "INVALID_USER",

  INVALID_QUESTION_ID: "INVALID_QUESTION_ID",
  QUESTION_MISSING_FIELDS: "QUESTION_MISSING_FIELDS",
  QUESTION_INVALID_USER: "QUESTION_INVALID_USER",
  QUESTION_ALREADY_EXISTS: "QUESTION_ALREADY_EXISTS",
  QUESTION_INVALID_ANSWER: "QUESTION_INVALID_ANSWER",
  QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",
  QUESTION_TYPE_INVALID: "QUESTION_TYPE_INVALID",
  QUESTION_ALREADY_ANSWERED: "QUESTION_ALREADY_ANSWERED",
  UNMATCH_WITH_QUESTIONTYPE: "UNMATCH_WITH_QUESTIONTYPE",

  ANSWER_NOT_FOUND: "ANSWER_NOT_FOUND",
  ANSWER_ID_NOT_FOUND: "ANSWER_ID_NOT_FOUND",

  INVALID_ANSWER_TYPE: "INVALID_ANSWER_TYPE",
  TITLE_FIELDS_ERROR: "TITLE_FIELDS_ERROR",
  ID_NOT_FOUND: "ID_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ERROR_ONE: "ERROR_ONE",
  NO_RANK_FOUND: "NO_RANK_FOUND",
  DUPLICATE: "DUPLICATE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
